name: Cypress Automation Tests
on:
  workflow_dispatch:
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
            fail-fast: false
            matrix:
             containers: [ 0, 1, 2, 3, 4,5 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npx cypress run --env allure=true grepTags=@regression --spec $(node cypress-parallel.js ${{ matrix.containers }} 6)
      
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history